### ISSUE TITLE
Can't talk with JDY-08

### ISSUE THREAD

**Issue by botletics** [kichMan/JDY-08#1]
Hi there,

Thanks for the info here! I have the correct wiring with TX/RX on pins P03 and P02, and PWRC connected to GND but it won't respond to AT commands. I am using 115200 baud and I've tried 9600 as well.

One weird thing though: I was playing around with it once, and I typed "AT+NAME?" and one time it randomly replied with some random stuff like " O C)" and it actually changed the name to "?". However, I don't know what I did there and I can't repeat it.

Any ideas what's going on?

**Comment by kichMan** [comment]
Hi!
This behavior is similar to an incorrect connection, which soft-terminal and with which settings did you connect to the module?

**Comment by botletics** [comment]
Thanks for the reply! I used the pinout on [this document](https://docs.google.com/document/d/14mHWT3GhELCj-6yxsam0k5bjzazq8nnPoz4B_gYh04k/edit#heading=h.lkl7kit1e1ct) and connected my Adafruit Feather 32u4 (3.3V logic) to the module with the following connections:

- 3.3V
- GND
- Bluetooth TX (Pin 19/P03) -> 32u4 SoftwareSerial RX (pin 10)
- Bluetooth RX (Pin 19/P02) -> 32u4 SoftwareSerial TX (pin 9)
- Pin 22/P00 (PWRC) -> GND (I tried with and without this)

**Comment by botletics** [comment]
Here is the code I used. It's very simple:

`#include <SoftwareSerial.h>

SoftwareSerial BT(10,9); // RX, TX  

void setup() {  
  Serial.begin(115200);
  BT.begin(115200); // Default baud rate
}

void loop() {  
  char c;
  if (Serial.available()) {
    c = Serial.read();
    BT.print(c);
  }
  if (BT.available()) {
    c = BT.read();
    Serial.print(c);    
  }
}`

**Comment by kichMan** [comment]
Try changing the code
Serial.print (s); -> Serial.write (c);
BT.print (c); -> Serial.write (c);

**Comment by kichMan** [comment]
Because, method print() on Arduino IDE not binary data
![arduino](https://user-images.githubusercontent.com/1647073/31142075-dcd09824-a881-11e7-9b32-7f4b3f5a905b.png)

**Comment by botletics** [comment]
OK thanks, I will try that. But which pins are correct, the Google docs or the Google image I showed you? And do I need the PWRC pin connected to GND?

**Comment by kichMan** [comment]
Also, you have two devices at the same speed - it's bad
`Serial.begin(115200);
BT.begin(115200); // Default baud rate`

**Comment by kichMan** [comment]
Pins are connected correctly. 
The Google docs and the Google image = are the same

**Comment by botletics** [comment]
The Google docs shows TX and RX on pins 19 and 20 but the image shows it on pins 5 and 6.

**Comment by kichMan** [comment]
Sorry, I'm going to double-check

**Comment by botletics** [comment]
The physical pinout is the same on both, but the usage is different.

**Comment by botletics** [comment]
I'm getting something now! But the stuff it sends back is weird. I am connecting TX/RX to pins P02 and P03 (like your Github page and Google docs say) and using 9600 baud for Serial Monitor, but 115200 baud for SoftwareSerial connection. I can successfully change the name and I get a reply ")OI" if I type in "AT+NAMETEST" and ")FQQ" when I type in "AT+MAC"

**Comment by botletics** [comment]
I get "YYd77⸮c⸮⸮⸮@FF8" when I send "AT+MAC"

**Comment by kichMan** [comment]
What instructions return "AT+NAME" and instructions after "AT+HOSTEN"?

**Comment by kichMan** [comment]
>> message "YYd77⸮c⸮⸮⸮@FF8"
My guess is that the software port module speed is incorrectly synchronized.

**Comment by botletics** [comment]
I'll try that and let you know later. I have to go now but will check back later. My ultimate goal for this module is to be able to send and receive data via Bluetooth to my phone. Can it do this? I have an HM-10 and it works, so I bought this since it's small.

**Comment by kichMan** [comment]
For testing JDY-08 on the phone, I used [this app](https://play.google.com/store/apps/details?id=com.hatflabs.hmbleterminal)

**Comment by botletics** [comment]
I am using 9600 baud for Serial Monitor with "Serial.begin(9600);" so that shouldn't be the problem. But yes, it does seem like a baud rate or synchronization issue.

**Comment by botletics** [comment]
Do you know the service and characteristic UUID's for this? Is it the same as HM-10?

**Comment by botletics** [comment]
Never mind, solved! I got it to work, thanks!

**Comment by botletics** [comment]
I am ablvle

**Comment by botletics** [comment]
I am able to receive data from the module and display it on my phone but I can't seem to send data to it. Do you know if the TX characteristic UUID the same as the RX characteristic UUID, as in the HM-10?

**Comment by botletics** [comment]
I can now properly receive AT command responses ("+OK", etc) after lowering the baud rate from the default. It's strange that the default baud doesn't work.

**Comment by botletics** [comment]
Latest update: Everything works now! It was super weird, I had to use the default 115200 baud to send the AT command "AT+BOUD1" to switch the baud rate to something slower so that it could be used, then do "AT+HOSTEN0" then use the new baud rate in my code. Now the characters show up correctly!

**Comment by kichMan** [comment]
1. What speed are you using now (what return command "AT+BOUD")?
2. What status does the "AT+HOSTEN" command return?
3. Can you show binary signal or hex (no Arduino IDE console)?

**Comment by kichMan** [comment]
Apparently, earlier you changed the mode of the module, because of this there were errors

**Comment by botletics** [comment]
1. I am using 57600 ("AT+BOUD1"). I suppose other baud rates would work too, but 115200 doesn't work.
2. "AT+HOSTEN" returns "+HOSTEN:0" as expected, because I set it to 0. It is set to 0 by default but doesn't work with 115200 baud.
3. How do I do the binary signal?

The strange thing is I never changed the mode of the module before this. If I switch back to 115200, I still will get garbled responses to the AT commands, but the AT commands will work. To me it seems like it simply doesn't operate well at the default 115200 baud.

**Comment by FF8** [comment]
Hello all,

Why am I part of this conversation?





2017-10-04 19:40 GMT+01:00 Timothy Woo <notifications@github.com>:

**Comment by botletics** [comment]
??

**Comment by FF8** [comment]
I am receiving notifications from this issue which I have never heard. Why
are you carbon copy these talk to me?








2017-10-05 14:35 GMT+01:00 Timothy Woo <notifications@github.com>:

**Comment by botletics** [comment]
Very strange indeed, I don't even know you lol.

**Comment by botletics** [comment]
Ohhhh, it's because "YYd77⸮c⸮⸮⸮@FF8" (which was a serial monitor response) happened to mention your name in it I think. Sorry about that lol.

**Comment by FF8** [comment]
LOL!

Now it's explained xD

2017-10-05 16:52 GMT+01:00 Timothy Woo <notifications@github.com>:

**Comment by kichMan** [comment]
xD
