### ISSUE TITLE
RTC Alarm

### ISSUE THREAD

**Issue by iyoruk31** [kichMan/JDY-08#10]
Hi @kichMan,

I couldn't find any information about setting and functionality of RTC alarm of JDY-08. It seems that there are two pins set/resets with RTC alarms but there is no information about them.

Do you know the details about setting and using RTC alarm?

Cheers!

**Comment by kichMan** [comment]
@iyoruk31 I tried to find a mention of RTC Alarm in the documentation, strangely, this item is in the feature descriptions, but not match in the commands.

**Comment by iyoruk31** [comment]
Thanks!
