### ISSUE TITLE
BLEPeripheral library

### ISSUE THREAD

**Issue by Vi-dot** [kichMan/JDY-08#2]
Hello @kichMan ,

I wonder if the JDY-08 or the JDY-09 (the one I'm using) could work with the [sandeepmistry's BLEPeripheral library](https://github.com/sandeepmistry/arduino-BLEPeripheral).

Configuration needed is :
- TX power in dBm
Pinouts : 
- REQ pin
- RDY pin
- RST pin, can be UNUSED

- manufacturerData

Do you know if the hardware is suitable ?

**Comment by kichMan** [comment]
No. Arduino BLEPeripheral on current day work only with BLE Nordic Semiconductor's. These are different microcontrollers.

**Comment by Vi-dot** [comment]
Ok thanks for your help. Then I'll try with your commands list.
