### ISSUE TITLE
scan stop

### ISSUE THREAD

**Issue by dariushabbasi** [kichMan/JDY-08#4]
I am following to connect two of them to each other . AT+HOSTEN1 AT+RST AT+SCAN1 but after a short time i recived +scan stop 
i connected it via TTL to serial port and just sending AT commands and nothing else in hardware I have done unless that connecting power

**Comment by kichMan** [comment]
What scheme did you connect and what target did you want to get?

**Comment by kichMan** [comment]
If you work with AT-commands, then you need to turn on the AT-mode, for this you need to hardware connect a pin P00

Look it this document by hardware connect:
https://github.com/kichMan/JDY-08/blob/master/KiCAD/datasheet.pdf

**Comment by dariushabbasi** [comment]
Thank you KichMan for your reply 
I really apologize you for asking this kind of question here.
AT commands are replying as I told , so I do not think I p00 is my point of mistake , it is disconnected now and many AT commands have reply.
my point is : after two At commands(  AT+HOSTEN1 AT+RST) reply OK .
AT+SCAN1 at first reply Ok also after a while it send to me +scan stop

actually when I connect POO to GND the AT COMMANDS dos not response at all but when ever I let it be disconnected to connect it yo 3.3v the AT commands are replying except that AT+SCAN1 which reply +OK+SCAN:STOP
Just now I have found that AT+ADVEN1 replied to be +ERR:1002 
I do not know why ? but I am sure the first of all I have to fix it .
could you please help me in this matter ?
