### ISSUE TITLE
Jdy-67 BLE connection problem

### ISSUE THREAD

**Issue by mahmoodpeeng** [kichMan/JDY-08#8]
Hi,
There is problem with jdy-67 ble connection with BLE serial APP with android, first there is a unknown password for bonding, second, no command execute after connect without bonded chip,
I just connect it with cp2102 but un successfull with BLE,
Can you help me thanks

**Comment by kichMan** [comment]
@mahmoodpeeng  Sorry, but the functionality of the jdy-67 module was not considered.

**Comment by kichMan** [comment]
not supported module
